POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Adrew Johns",
  "number": "33-42324"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "040-123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "39-44-5323523"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Dan Abramov",
  "number": "12-43-234345"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mary Poppendieck",
  "number": "39-23-6423122"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Marelyn Grove",
  "number": "020-232312"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Lee",
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "33-42324"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Wu Tao",
  "number": "00-123456"
}