POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Adrew Johns",
  "number": "33-42324"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "33-42324"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Lee",
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "33-42324"
}